apiVersion: v1
kind: ConfigMap
metadata:
  name: nodejs-web-config 
data:
  APP_ENV: "dev"
  APP_OS: "ubuntu/nodejs"
  APP_NETWORK: "NodePort/30005"
  welcome.message: "Welcome to the NodeJS Web App on Minikube"