apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-web-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/nodejs-web"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-web-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
   requests:
    storage: 512Mi